// Generated by CoffeeScript 1.6.3
(function() {
  var app, express, port;

  express = require("express");

  app = express();

  port = 8000;

  if (process.env.NODE_ENV === 'production') {
    port = 80;
  } else {
    port = process.env.PORT || port;
  }

  console.log("listening on port " + port);

  app.listen(port);

  app.use(express.bodyParser());

  app.use(function(req, res, next) {
    console.log("\n " + req.method + " " + req.url);
    next();
    return null;
  });

  app.get('/', function(req, res) {
    res.sendfile("index.html");
    return null;
  });

  app.use(express["static"](__dirname));

}).call(this);
