// Generated by CoffeeScript 1.6.3
(function() {
  var app, express;

  express = require("express");

  app = express();

  app.listen(process.env.PORT || 8000);

  app.use(express.bodyParser());

  app.use(function(req, res, next) {
    console.log("\n " + req.method + " " + req.url);
    next();
    return null;
  });

  app.get('/', function(req, res) {
    res.sendfile("index.html");
    return null;
  });

  app.use(express["static"](__dirname));

}).call(this);
