// Generated by CoffeeScript 1.6.3
(function() {
  var app, express, port;

  express = require("express");

  app = express();

  port = 3001;

  app.listen(port, function() {
    console.log("Listening on port " + port);
    return null;
  });

  app.use(express.bodyParser());

  app.use(function(req, res, next) {
    console.log("\n " + req.method + " " + req.url);
    next();
    return null;
  });

  app.get('/', function(req, res) {
    res.sendfile("" + __dirname + "/index.html");
    return null;
  });

  app.use(express["static"](__dirname));

}).call(this);
